from __future__ import annotations

from dataclasses import dataclass

from pkgwhy.core.models import Confidence, RiskRuleEvidence, RuleCategory, RuleSeverity


@dataclass(frozen=True)
class RuleDefinition:
    """Stable metadata for one pre-alpha risk rule."""

    rule_id: str
    name: str
    category: RuleCategory
    severity: RuleSeverity
    confidence: Confidence
    default_message: str
    false_positive_note: str | None = None


RULES: dict[str, RuleDefinition] = {
    "PKGWHY-VULN-001": RuleDefinition(
        rule_id="PKGWHY-VULN-001",
        name="known_vulnerability_match",
        category=RuleCategory.VULNERABILITY,
        severity=RuleSeverity.HIGH,
        confidence=Confidence.MEDIUM,
        default_message="Known vulnerability advisory matched this package version.",
        false_positive_note="Advisory databases can be incomplete or imprecise; verify the source advisory and version range.",
    ),
    "PKGWHY-RISK-001": RuleDefinition(
        rule_id="PKGWHY-RISK-001",
        name="possible_typosquat_similarity",
        category=RuleCategory.IDENTITY,
        severity=RuleSeverity.MEDIUM,
        confidence=Confidence.MEDIUM,
        default_message="Package name is similar to a popular package name.",
        false_positive_note="Legitimate ecosystem packages can share prefixes or naming families.",
    ),
    "PKGWHY-RISK-002": RuleDefinition(
        rule_id="PKGWHY-RISK-002",
        name="source_availability_unknown",
        category=RuleCategory.SOURCE,
        severity=RuleSeverity.MEDIUM,
        confidence=Confidence.MEDIUM,
        default_message="Source availability is unknown from installed files.",
        false_positive_note="Some legitimate packages ship metadata-only wheels or generated artifacts.",
    ),
    "PKGWHY-RISK-003": RuleDefinition(
        rule_id="PKGWHY-RISK-003",
        name="missing_license_metadata",
        category=RuleCategory.METADATA,
        severity=RuleSeverity.MEDIUM,
        confidence=Confidence.MEDIUM,
        default_message="Installed metadata does not include a clear license value.",
        false_positive_note="License metadata can be omitted even when licensing is documented elsewhere.",
    ),
    "PKGWHY-RISK-004": RuleDefinition(
        rule_id="PKGWHY-RISK-004",
        name="native_compiled_code_present",
        category=RuleCategory.BINARY,
        severity=RuleSeverity.MEDIUM,
        confidence=Confidence.MEDIUM,
        default_message="Native compiled files are present.",
        false_positive_note="Native extensions are common in legitimate numerical, cryptographic, and performance packages.",
    ),
    "PKGWHY-RISK-005": RuleDefinition(
        rule_id="PKGWHY-RISK-005",
        name="static_capability_signal",
        category=RuleCategory.STATIC_ANALYSIS,
        severity=RuleSeverity.MEDIUM,
        confidence=Confidence.MEDIUM,
        default_message="Static capability signal detected.",
        false_positive_note="Static references are not proof of runtime behavior, intent, or unsafe use.",
    ),
    "PKGWHY-RISK-006": RuleDefinition(
        rule_id="PKGWHY-RISK-006",
        name="no_installed_files_found",
        category=RuleCategory.METADATA,
        severity=RuleSeverity.HIGH,
        confidence=Confidence.LOW,
        default_message="No installed package files were found through distribution metadata.",
        false_positive_note="Editable installs or unusual packaging layouts can hide files from distribution metadata.",
    ),
    "PKGWHY-PY-001": RuleDefinition(
        rule_id="PKGWHY-PY-001",
        name="python_dynamic_code_execution",
        category=RuleCategory.STATIC_ANALYSIS,
        severity=RuleSeverity.HIGH,
        confidence=Confidence.HIGH,
        default_message="Python dynamic code execution construct referenced.",
        false_positive_note="Dynamic execution can be legitimate in frameworks, plugins, and compatibility layers.",
    ),
    "PKGWHY-PY-002": RuleDefinition(
        rule_id="PKGWHY-PY-002",
        name="python_dynamic_import",
        category=RuleCategory.STATIC_ANALYSIS,
        severity=RuleSeverity.MEDIUM,
        confidence=Confidence.HIGH,
        default_message="Python dynamic import construct referenced.",
        false_positive_note="Dynamic imports are common in plugin systems and optional dependency loading.",
    ),
    "PKGWHY-PY-003": RuleDefinition(
        rule_id="PKGWHY-PY-003",
        name="python_deserialisation_risk",
        category=RuleCategory.STATIC_ANALYSIS,
        severity=RuleSeverity.HIGH,
        confidence=Confidence.HIGH,
        default_message="Python deserialisation-risk construct referenced.",
        false_positive_note="Deserialisation APIs can be safe when inputs are trusted and validated.",
    ),
    "PKGWHY-PY-004": RuleDefinition(
        rule_id="PKGWHY-PY-004",
        name="python_encoded_payload_handling",
        category=RuleCategory.STATIC_ANALYSIS,
        severity=RuleSeverity.MEDIUM,
        confidence=Confidence.HIGH,
        default_message="Python encoded-payload handling construct referenced.",
        false_positive_note="Encoding and compression APIs are common in legitimate data processing code.",
    ),
    "PKGWHY-PY-005": RuleDefinition(
        rule_id="PKGWHY-PY-005",
        name="python_subprocess_or_shell_execution",
        category=RuleCategory.STATIC_ANALYSIS,
        severity=RuleSeverity.HIGH,
        confidence=Confidence.HIGH,
        default_message="Python subprocess or shell execution construct referenced.",
        false_positive_note="Subprocess APIs can be legitimate for CLI wrappers, build tools, and integrations.",
    ),
    "PKGWHY-PY-006": RuleDefinition(
        rule_id="PKGWHY-PY-006",
        name="python_environment_or_secret_access",
        category=RuleCategory.STATIC_ANALYSIS,
        severity=RuleSeverity.MEDIUM,
        confidence=Confidence.MEDIUM,
        default_message="Python environment or secret-like access pattern referenced.",
        false_positive_note="Environment variable and credential-like names can appear in legitimate configuration code.",
    ),
    "PKGWHY-PY-007": RuleDefinition(
        rule_id="PKGWHY-PY-007",
        name="python_package_manager_manipulation",
        category=RuleCategory.STATIC_ANALYSIS,
        severity=RuleSeverity.HIGH,
        confidence=Confidence.MEDIUM,
        default_message="Python package-manager manipulation pattern referenced.",
        false_positive_note="Installer wrappers and build tooling may legitimately invoke package managers.",
    ),
    "PKGWHY-PY-008": RuleDefinition(
        rule_id="PKGWHY-PY-008",
        name="python_unsafe_yaml_load",
        category=RuleCategory.STATIC_ANALYSIS,
        severity=RuleSeverity.HIGH,
        confidence=Confidence.HIGH,
        default_message="Python unsafe YAML load construct referenced.",
        false_positive_note="YAML loading can be safe when using safe loaders or trusted inputs; review call arguments.",
    ),
    "PKGWHY-PY-009": RuleDefinition(
        rule_id="PKGWHY-PY-009",
        name="python_obfuscation_bootstrap_signal",
        category=RuleCategory.STATIC_ANALYSIS,
        severity=RuleSeverity.HIGH,
        confidence=Confidence.MEDIUM,
        default_message="Python obfuscation-bootstrap pattern referenced.",
        false_positive_note="Obfuscation-bootstrap names can appear in comments, fixtures, or vendored compatibility code.",
    ),
    "PKGWHY-BUILD-001": RuleDefinition(
        rule_id="PKGWHY-BUILD-001",
        name="executable_setup_py_present",
        category=RuleCategory.STATIC_ANALYSIS,
        severity=RuleSeverity.MEDIUM,
        confidence=Confidence.HIGH,
        default_message="Executable setup.py file is present.",
        false_positive_note="Many legacy packages include setup.py; presence alone is not proof of unsafe install behavior.",
    ),
    "PKGWHY-BUILD-002": RuleDefinition(
        rule_id="PKGWHY-BUILD-002",
        name="setup_time_subprocess_signal",
        category=RuleCategory.STATIC_ANALYSIS,
        severity=RuleSeverity.HIGH,
        confidence=Confidence.MEDIUM,
        default_message="setup.py contains subprocess or shell execution references.",
        false_positive_note="Build scripts can legitimately invoke compilers or local build tools.",
    ),
    "PKGWHY-BUILD-003": RuleDefinition(
        rule_id="PKGWHY-BUILD-003",
        name="setup_time_network_signal",
        category=RuleCategory.STATIC_ANALYSIS,
        severity=RuleSeverity.HIGH,
        confidence=Confidence.MEDIUM,
        default_message="setup.py contains network access references.",
        false_positive_note="Build scripts can reference network libraries without using them during installation.",
    ),
    "PKGWHY-BUILD-004": RuleDefinition(
        rule_id="PKGWHY-BUILD-004",
        name="setup_time_dynamic_execution_signal",
        category=RuleCategory.STATIC_ANALYSIS,
        severity=RuleSeverity.HIGH,
        confidence=Confidence.MEDIUM,
        default_message="setup.py contains dynamic execution references.",
        false_positive_note="Dynamic execution references can appear in compatibility logic; inspect context manually.",
    ),
    "PKGWHY-BUILD-005": RuleDefinition(
        rule_id="PKGWHY-BUILD-005",
        name="build_backend_declared",
        category=RuleCategory.METADATA,
        severity=RuleSeverity.INFO,
        confidence=Confidence.HIGH,
        default_message="Build backend metadata is declared.",
        false_positive_note="Declarative build metadata is informational unless paired with other suspicious signals.",
    ),
    "PKGWHY-BUILD-006": RuleDefinition(
        rule_id="PKGWHY-BUILD-006",
        name="setup_cfg_present",
        category=RuleCategory.METADATA,
        severity=RuleSeverity.INFO,
        confidence=Confidence.HIGH,
        default_message="setup.cfg metadata file is present.",
        false_positive_note="setup.cfg is usually declarative metadata and is not executable Python code.",
    ),
    "PKGWHY-NET-001": RuleDefinition(
        rule_id="PKGWHY-NET-001",
        name="source_url_or_domain_reference",
        category=RuleCategory.STATIC_ANALYSIS,
        severity=RuleSeverity.LOW,
        confidence=Confidence.MEDIUM,
        default_message="Source text references a URL or domain.",
        false_positive_note="URL references can be documentation, examples, tests, or metadata and are not proof of network behavior.",
    ),
    "PKGWHY-CRED-001": RuleDefinition(
        rule_id="PKGWHY-CRED-001",
        name="credential_like_assignment",
        category=RuleCategory.STATIC_ANALYSIS,
        severity=RuleSeverity.MEDIUM,
        confidence=Confidence.MEDIUM,
        default_message="Source text contains a credential-like assignment pattern.",
        false_positive_note="Credential-like names can appear in placeholders, tests, documentation, and configuration examples.",
    ),
    "PKGWHY-JS-001": RuleDefinition(
        rule_id="PKGWHY-JS-001",
        name="javascript_minification_signal",
        category=RuleCategory.STATIC_ANALYSIS,
        severity=RuleSeverity.LOW,
        confidence=Confidence.MEDIUM,
        default_message="JavaScript minification or density signal detected.",
        false_positive_note="Minified JavaScript is common in legitimate distributions and is not automatically suspicious.",
    ),
    "PKGWHY-JS-002": RuleDefinition(
        rule_id="PKGWHY-JS-002",
        name="javascript_dynamic_execution_signal",
        category=RuleCategory.STATIC_ANALYSIS,
        severity=RuleSeverity.HIGH,
        confidence=Confidence.HIGH,
        default_message="JavaScript dynamic execution construct referenced.",
        false_positive_note="Dynamic JavaScript execution can be legitimate in loaders and compatibility code; inspect context manually.",
    ),
    "PKGWHY-JS-003": RuleDefinition(
        rule_id="PKGWHY-JS-003",
        name="javascript_encoded_payload_signal",
        category=RuleCategory.STATIC_ANALYSIS,
        severity=RuleSeverity.MEDIUM,
        confidence=Confidence.MEDIUM,
        default_message="JavaScript encoded-payload handling signal detected.",
        false_positive_note="Encoding APIs and encoded strings can be legitimate in bundled assets and data fixtures.",
    ),
    "PKGWHY-JS-004": RuleDefinition(
        rule_id="PKGWHY-JS-004",
        name="javascript_obfuscation_signal",
        category=RuleCategory.STATIC_ANALYSIS,
        severity=RuleSeverity.MEDIUM,
        confidence=Confidence.MEDIUM,
        default_message="JavaScript obfuscation-like pattern detected.",
        false_positive_note="Obfuscation-like patterns can appear in generated or bundled code; they require context-sensitive review.",
    ),
    "PKGWHY-JS-005": RuleDefinition(
        rule_id="PKGWHY-JS-005",
        name="javascript_source_map_reference",
        category=RuleCategory.STATIC_ANALYSIS,
        severity=RuleSeverity.INFO,
        confidence=Confidence.HIGH,
        default_message="JavaScript source-map reference detected.",
        false_positive_note="Source maps are often helpful debug metadata and are not a security issue by themselves.",
    ),
    "PKGWHY-BIN-001": RuleDefinition(
        rule_id="PKGWHY-BIN-001",
        name="native_extension_present",
        category=RuleCategory.BINARY,
        severity=RuleSeverity.MEDIUM,
        confidence=Confidence.HIGH,
        default_message="Native compiled extension or library file is present.",
        false_positive_note="Native extensions are common in legitimate numerical, cryptographic, and performance packages.",
    ),
    "PKGWHY-BIN-002": RuleDefinition(
        rule_id="PKGWHY-BIN-002",
        name="wasm_binary_present",
        category=RuleCategory.BINARY,
        severity=RuleSeverity.MEDIUM,
        confidence=Confidence.HIGH,
        default_message="WebAssembly binary file is present.",
        false_positive_note="WASM can be legitimate for portable performance-sensitive code and is not automatically malicious.",
    ),
    "PKGWHY-BIN-003": RuleDefinition(
        rule_id="PKGWHY-BIN-003",
        name="native_executable_present",
        category=RuleCategory.BINARY,
        severity=RuleSeverity.HIGH,
        confidence=Confidence.HIGH,
        default_message="Native executable file is present.",
        false_positive_note="Executable files can be legitimate helper tools, but should be reviewed before agent or production use.",
    ),
}


def make_rule_evidence(
    rule_id: str,
    *,
    message: str | None = None,
    evidence: list[str] | None = None,
    severity: RuleSeverity | None = None,
    confidence: Confidence | None = None,
    file_path: str | None = None,
    line_number: int | None = None,
    symbol: str | None = None,
) -> RiskRuleEvidence:
    definition = RULES[rule_id]
    return RiskRuleEvidence(
        rule_id=definition.rule_id,
        name=definition.name,
        category=definition.category,
        severity=severity or definition.severity,
        confidence=confidence or definition.confidence,
        message=message or definition.default_message,
        evidence=evidence or [],
        file_path=file_path,
        line_number=line_number,
        symbol=symbol,
        false_positive_note=definition.false_positive_note,
    )
